#!/usr/bin/env php
<?php

// defined('YII_DEBUG') or define('YII_DEBUG', true);

require(__DIR__ . '/../protected/config/mode.php');
require(__DIR__ . '/../vendor/autoload.php');

\power\yii2\log\LogHelper::init();
$config = require(__DIR__ . '/../protected/config/' . strtolower(APPLICATION_ENV) . '/console.php');
$exitCode = (new yii\console\Application($config))->run();
exit($exitCode);
